import os

CHAT_WEBSOCKET_SERVER_CERT_PATH = os.environ.get("CHAT_WEBSOCKET_SERVER_CERT_PATH")
CHAT_WEBSOCKET_SERVER_KEY_PATH = os.environ.get("CHAT_WEBSOCKET_SERVER_KEY_PATH")
CHAT_WEBSOCKET_SERVER_IP = os.environ.get("CHAT_WEBSOCKET_SERVER_IP", "localhost")
CHAT_WEBSOCKET_SERVER_PORT = os.environ.get("CHAT_WEBSOCKET_SERVER_PORT", 6789)
